import { useCallback, useEffect, useState } from 'react'
import { request } from '../lib/api'
import type { Session } from './AuthScreen'

type Dashboard = { totalHosts: number; totalEvents: number; totalPhotos: number; photoBytes: number; totalQrCodes: number; usedQrCodes: number; publicGalleries: number; monthly: { month: string; events: number; photos: number; qrCodes: number; usedQrCodes: number; photoBytes: number }[]; events: EventMetric[] }
type EventMetric = { eventId: string; eventName: string; hostEmail: string; photos: number; photoBytes: number; qrCodes: number; usedQrCodes: number; publicGalleries: number }
type Host = { id: string; name: string; email: string; isActive: boolean; isBlocked: boolean; isAdmin: boolean; eventCount: number }
type AuditItem = { id: string; actorType: string; action: string; entityType: string; metadata?: string; createdAt: string }
const bytes = (value: number) => value > 1e9 ? `${(value / 1e9).toFixed(1)} GB` : `${(value / 1e6).toFixed(1)} MB`

export function AdminScreen({ session, onBack }: { session: Session; onBack: () => void }) {
  const [data, setData] = useState<Dashboard | null>(null); const [hosts, setHosts] = useState<Host[]>([]); const [audit, setAudit] = useState<AuditItem[]>([]); const [message, setMessage] = useState('')
  const load = useCallback(async () => { try { const [dashboard, hostPage, auditItems] = await Promise.all([request<Dashboard>('/api/admin/dashboard'), request<{ items: Host[] }>('/api/admin/hosts'), request<AuditItem[]>('/api/admin/audit')]); setData(dashboard); setHosts(hostPage.items); setAudit(auditItems) } catch (error) { setMessage(error instanceof Error ? error.message : 'Admin məlumatları yüklənmədi.') } }, [])
  useEffect(() => { void load() }, [load])
  async function toggle(host: Host) { try { await request(`/api/admin/hosts/${host.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: host.isActive, isBlocked: !host.isBlocked, blockedReason: host.isBlocked ? null : 'Administrator tərəfindən bloklanıb' }) }); await load() } catch { setMessage('Host statusu yenilənmədi.') } }
  async function deleteEvent(item: EventMetric) { if (!window.confirm(`“${item.eventName}” soft-delete edilsin?`)) return; try { await request(`/api/admin/events/${item.eventId}`, { method: 'DELETE' }); await load() } catch { setMessage('Event silinə bilmədi.') } }
  if (!session.isAdmin) return <main className="app-shell"><p className="error">Bu səhifə yalnız administrator üçündür.</p></main>
  return <main className="dashboard-shell"><header className="dashboard-header"><img className="header-logo" src="/brand/bizden-logo.png" alt="Bizdən" /><div><strong>Admin panel</strong><span>{session.email}</span></div><button className="text-button" onClick={onBack}>← Dashboard</button></header>{message ? <p className="error">{message}</p> : null}{!data ? <p className="muted">Yüklənir...</p> : <div className="workspace admin-workspace"><section className="admin-kpis">{[[data.totalHosts,'Host'],[data.totalEvents,'Event'],[data.totalPhotos,'Foto'],[bytes(data.photoBytes),'Storage'],[`${data.usedQrCodes}/${data.totalQrCodes}`,'İstifadə edilən QR'],[data.publicGalleries,'Public gallery']].map(([value,label]) => <article className="panel" key={String(label)}><strong>{value}</strong><span>{label}</span></article>)}</section><AdminTable title="Aylıq axın" headers={['Ay','Event','Foto','QR / istifadə','Həcm']} rows={data.monthly.map(item => [item.month,item.events,item.photos,`${item.usedQrCodes}/${item.qrCodes}`,bytes(item.photoBytes)])} /><section className="panel"><h2>Host idarəetməsi</h2><div className="admin-table"><table><thead><tr><th>Ad</th><th>Email</th><th>Event</th><th>Status</th><th></th></tr></thead><tbody>{hosts.map(host => <tr key={host.id}><td>{host.name}{host.isAdmin ? ' · admin' : ''}</td><td>{host.email}</td><td>{host.eventCount}</td><td>{host.isBlocked ? 'Bloklanıb' : host.isActive ? 'Aktiv' : 'Deaktiv'}</td><td><button className="text-button" onClick={() => void toggle(host)}>{host.isBlocked ? 'Bloku aç' : 'Blokla'}</button></td></tr>)}</tbody></table></div></section><section className="panel"><h2>Event audit</h2><div className="admin-table"><table><thead><tr><th>Event</th><th>Host</th><th>Foto</th><th>QR</th><th>Public</th><th>Həcm</th><th></th></tr></thead><tbody>{data.events.map(item => <tr key={item.eventId}><td>{item.eventName}</td><td>{item.hostEmail}</td><td>{item.photos}</td><td>{item.usedQrCodes}/{item.qrCodes}</td><td>{item.publicGalleries}</td><td>{bytes(item.photoBytes)}</td><td><button className="danger-button" onClick={() => void deleteEvent(item)}>Sil</button></td></tr>)}</tbody></table></div></section><AdminTable title="Son audit log" headers={['Vaxt','Actor','Action','Entity','Detallar']} rows={audit.map(item => [new Date(item.createdAt).toLocaleString(),item.actorType,item.action,item.entityType,item.metadata ?? '—'])} /></div>}</main>
}

function AdminTable({ title, headers, rows }: { title: string; headers: string[]; rows: (string | number)[][] }) { return <section className="panel"><h2>{title}</h2><div className="admin-table"><table><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${title}-${index}`}>{row.map((value, cell) => <td key={cell}>{value}</td>)}</tr>)}</tbody></table></div></section> }
