import { useCallback, useEffect, useState } from 'react'
import { request } from '../lib/api'
import type { Session } from './AuthScreen'

type Dashboard = { totalHosts: number; activeHosts: number; totalEvents: number; totalPhotos: number; photoBytes: number; totalQrCodes: number; usedQrCodes: number; publicGalleries: number; monthly: { month: string; events: number; photos: number; qrCodes: number; usedQrCodes: number; photoBytes: number }[]; events: { eventId: string; eventName: string; hostEmail: string; photos: number; photoBytes: number; qrCodes: number; usedQrCodes: number; publicGalleries: number }[] }
type Host = { id: string; name: string; email: string; isActive: boolean; isBlocked: boolean; isAdmin: boolean; eventCount: number }

const bytes = (value: number) => value > 1_000_000_000 ? `${(value / 1_000_000_000).toFixed(1)} GB` : `${(value / 1_000_000).toFixed(1)} MB`

export function AdminScreen({ session, onBack }: { session: Session; onBack: () => void }) {
  const [data, setData] = useState<Dashboard | null>(null)
  const [hosts, setHosts] = useState<Host[]>([])
  const [message, setMessage] = useState('')
  const load = useCallback(async () => { try { const [dashboard, hostPage] = await Promise.all([request<Dashboard>('/api/admin/dashboard'), request<{ items: Host[] }>('/api/admin/hosts')]); setData(dashboard); setHosts(hostPage.items) } catch (error) { setMessage(error instanceof Error ? error.message : 'Admin məlumatları yüklənmədi.') } }, [])
  useEffect(() => { void load() }, [load])
  async function toggle(host: Host) { try { await request(`/api/admin/hosts/${host.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: host.isActive, isBlocked: !host.isBlocked, blockedReason: host.isBlocked ? null : 'Administrator tərəfindən bloklanıb' }) }); await load() } catch { setMessage('Host statusu yenilənmədi.') } }
  if (!session.isAdmin) return <main className="app-shell"><p className="error">Bu səhifə yalnız administrator üçündür.</p></main>
  return <main className="dashboard-shell"><header className="dashboard-header"><img className="header-logo" src="/brand/bizden-logo.png" alt="Bizdən" /><div><strong>Admin panel</strong><span>{session.email}</span></div><button className="text-button" onClick={onBack}>← Dashboard</button></header>{message ? <p className="error">{message}</p> : null}{!data ? <p className="muted">Yüklənir...</p> : <div className="workspace admin-workspace"><section className="admin-kpis"><article className="panel"><strong>{data.totalHosts}</strong><span>Host</span></article><article className="panel"><strong>{data.totalEvents}</strong><span>Event</span></article><article className="panel"><strong>{data.totalPhotos}</strong><span>Foto</span></article><article className="panel"><strong>{bytes(data.photoBytes)}</strong><span>Storage</span></article><article className="panel"><strong>{data.usedQrCodes}/{data.totalQrCodes}</strong><span>İstifadə edilən QR</span></article><article className="panel"><strong>{data.publicGalleries}</strong><span>Public gallery</span></article></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Audit statistikası</p><h2>Aylıq axın</h2></div></div><div className="admin-table"><table><thead><tr><th>Ay</th><th>Event</th><th>Foto</th><th>QR / istifadə</th><th>Həcm</th></tr></thead><tbody>{data.monthly.map(item => <tr key={item.month}><td>{item.month}</td><td>{item.events}</td><td>{item.photos}</td><td>{item.usedQrCodes}/{item.qrCodes}</td><td>{bytes(item.photoBytes)}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Host idarəetməsi</p><h2>İstifadəçilər</h2></div></div><div className="admin-table"><table><thead><tr><th>Ad</th><th>Email</th><th>Event</th><th>Status</th><th></th></tr></thead><tbody>{hosts.map(host => <tr key={host.id}><td>{host.name}{host.isAdmin ? ' · admin' : ''}</td><td>{host.email}</td><td>{host.eventCount}</td><td>{host.isBlocked ? 'Bloklanıb' : host.isActive ? 'Aktiv' : 'Deaktiv'}</td><td><button className="text-button" onClick={() => void toggle(host)}>{host.isBlocked ? 'Bloku aç' : 'Blokla'}</button></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Event audit</p><h2>Son eventlər</h2></div></div><div className="admin-table"><table><thead><tr><th>Event</th><th>Host</th><th>Foto</th><th>QR</th><th>Public</th><th>Həcm</th></tr></thead><tbody>{data.events.map(item => <tr key={item.eventId}><td>{item.eventName}</td><td>{item.hostEmail}</td><td>{item.photos}</td><td>{item.usedQrCodes}/{item.qrCodes}</td><td>{item.publicGalleries}</td><td>{bytes(item.photoBytes)}</td></tr>)}</tbody></table></div></section></div>}</main>
}
