import { useState } from 'react'
import type { FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { request } from '../lib/api'

export type Session = { id: string; name: string; email: string; isAdmin?: boolean }
type AuthMode = 'login' | 'register' | 'verify' | 'reset-request' | 'reset-confirm'

export function AuthScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const { t } = useTranslation(); const [mode, setMode] = useState<AuthMode>('login'); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const [showPassword, setShowPassword] = useState(false)
  const reset = (next: AuthMode) => { setMode(next); setMessage('') }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const submittedEmail = String(form.get('email') ?? email); setIsSubmitting(true); setMessage('')
    try {
      if (mode === 'verify') onAuthenticated(await request<Session>('/api/host/auth/verify-email', { method: 'POST', body: JSON.stringify({ email, code: form.get('code') }) }))
      else if (mode === 'reset-request') { await request('/api/host/auth/password-reset/request', { method: 'POST', body: JSON.stringify({ email: submittedEmail }) }); setEmail(submittedEmail); reset('reset-confirm'); setMessage(t('auth.resetSent')) }
      else if (mode === 'reset-confirm') { await request('/api/host/auth/password-reset/confirm', { method: 'POST', body: JSON.stringify({ email, code: form.get('code'), password: form.get('password') }) }); reset('login'); setMessage(t('auth.passwordUpdated')) }
      else { const isRegistering = mode === 'register'; const result = await request<Session | { requiresEmailVerification: true }>(`/api/host/auth/${isRegistering ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(isRegistering ? { name: form.get('name'), email: submittedEmail, password: form.get('password') } : { email: submittedEmail, password: form.get('password') }) }); if ('requiresEmailVerification' in result) { setEmail(submittedEmail); reset('verify') } else onAuthenticated(result) }
    } catch (error) { setMessage(error instanceof Error ? error.message : t('auth.requestFailed')) } finally { setIsSubmitting(false) }
  }
  async function resend() { setIsSubmitting(true); setMessage(''); try { await request('/api/host/auth/resend-verification', { method: 'POST', body: JSON.stringify({ email }) }); setMessage(t('auth.codeSent')) } catch (error) { setMessage(error instanceof Error ? error.message : t('auth.resendFailed')) } finally { setIsSubmitting(false) } }
  const isRegistering = mode === 'register'; const isReset = mode === 'reset-request' || mode === 'reset-confirm'; const title = mode === 'verify' ? t('auth.enterCode') : mode === 'reset-request' ? t('auth.resetPassword') : mode === 'reset-confirm' ? t('auth.newPassword') : isRegistering ? t('auth.createAccount') : t('auth.welcome')
  return <main className="app-shell"><section className="auth-card" aria-labelledby="page-title"><img className="brand-logo" src="/brand/bizden-logo.png" alt="Bizdən" /><p className="eyebrow">{mode === 'verify' ? t('auth.emailVerification') : isReset ? t('auth.accountRecovery') : t('auth.hostPortal')}</p><h1 id="page-title">{title}</h1><p className="description">{mode === 'verify' ? t('auth.codeSentTo', { email }) : isReset ? t('auth.resetHelp') : t('auth.manageMemories')}</p><form onSubmit={submit}>{mode !== 'verify' && mode !== 'reset-confirm' ? <label>{t('auth.email')}<input name="email" type="email" defaultValue={email} required maxLength={256} autoComplete="email" /></label> : null}{isRegistering ? <label>{t('auth.name')}<input name="name" required maxLength={120} autoComplete="name" /></label> : null}{mode === 'verify' || mode === 'reset-confirm' ? <label>{t('auth.confirmationCode')}<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required /></label> : null}{mode !== 'verify' && mode !== 'reset-request' ? <label>{t('auth.password')}<span className="password-field"><input name="password" type={showPassword ? 'text' : 'password'} required minLength={isRegistering || mode === 'reset-confirm' ? 8 : undefined} pattern={isRegistering || mode === 'reset-confirm' ? '.*[0-9].*' : undefined} title={t('auth.passwordHint')} autoComplete={isRegistering || mode === 'reset-confirm' ? 'new-password' : 'current-password'} /><button type="button" className="password-toggle" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? t('auth.hidePassword') : t('auth.showPassword')}>{showPassword ? t('auth.hidePassword') : t('auth.showPassword')}</button></span>{isRegistering || mode === 'reset-confirm' ? <small>{t('auth.passwordHint')}</small> : null}</label> : null}{message ? <p className="error" role="alert">{message}</p> : null}<button className="primary" disabled={isSubmitting}>{isSubmitting ? t('auth.wait') : mode === 'verify' ? t('auth.verify') : mode === 'reset-request' ? t('auth.sendCode') : mode === 'reset-confirm' ? t('auth.updatePassword') : isRegistering ? t('register') : t('login')}</button></form>{mode === 'verify' ? <><button className="switch" type="button" disabled={isSubmitting} onClick={() => void resend()}>{t('auth.resendCode')}</button><button className="switch" type="button" onClick={() => reset('register')}>{t('auth.useAnotherEmail')}</button></> : mode === 'login' ? <><button className="switch" type="button" onClick={() => reset('reset-request')}>{t('auth.forgotPassword')}</button><button className="switch" type="button" onClick={() => reset('register')}>{t('auth.noAccount')}</button></> : <button className="switch" type="button" onClick={() => reset('login')}>{t('auth.backToLogin')}</button>}</section></main>
}
