import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { request } from '../lib/api'

type PublicGallery = { eventName: string; description?: string; eventDate: string; brandColor?: string; customMessage?: string; coverUrl?: string; photos: { id: string; originalFileName: string; uploadedAt: string; thumbnailUrl?: string; previewUrl?: string }[] }

export function PublicGalleryScreen({ publicId }: { publicId: string }) {
  const [info, setInfo] = useState<PublicGallery | null>(null); const [gallery, setGallery] = useState<PublicGallery | null>(null); const [message, setMessage] = useState(''); const [selected, setSelected] = useState<PublicGallery['photos'][number] | null>(null)
  useEffect(() => { void request<PublicGallery>(`/api/public/galleries/${publicId}`).then(setInfo).catch(() => setMessage('Bu qalereya əlçatan deyil.')) }, [publicId])
  async function unlock(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); setMessage(''); try { setGallery(await request<PublicGallery>(`/api/public/galleries/${publicId}/unlock`, { method: 'POST', body: JSON.stringify({ pin: new FormData(formEvent.currentTarget).get('pin') }) })) } catch { setMessage('PIN düzgün deyil və ya qalereya əlçatan deyil.') } }
  if (!info) return <main className="guest-shell"><section className="guest-card"><p className="error">{message || 'Yüklənir...'}</p></section></main>
  if (!gallery) return <main className="guest-shell"><section className="guest-card" style={{ borderColor: info.brandColor }}><img className="brand-logo" src="/brand/bizden-logo.png" alt="Bizdən" />{info.coverUrl ? <img className="gallery-cover" src={info.coverUrl} alt="" /> : null}<p className="eyebrow">Paylaşılan qalereya</p><h1>{info.eventName}</h1><p className="description">{info.customMessage || info.description || 'Fotolara baxmaq üçün hostun paylaşdığı PIN-i daxil edin.'}</p><form onSubmit={unlock}><label>PIN<input name="pin" inputMode="numeric" pattern="[0-9]{4,12}" minLength={4} maxLength={12} required autoFocus /></label><button className="primary" style={{ backgroundColor: info.brandColor }}>Qalereyanı aç</button></form>{message ? <p className="error" role="alert">{message}</p> : null}</section></main>
  return <main className="public-gallery-shell"><header className="public-gallery-head"><img className="header-logo" src="/brand/bizden-logo.png" alt="Bizdən" />{gallery.coverUrl ? <img className="gallery-cover" src={gallery.coverUrl} alt="" /> : null}<div><p className="eyebrow" style={{ color: gallery.brandColor }}>Paylaşılan xatirələr</p><h1>{gallery.eventName}</h1><p className="description">{gallery.customMessage || gallery.description}</p></div></header><div className="public-photo-grid">{gallery.photos.map(photo => <button className="public-photo" type="button" key={photo.id} onClick={() => setSelected(photo)}>{photo.thumbnailUrl ? <img src={photo.thumbnailUrl} alt={photo.originalFileName} /> : <span>Önizləmə hazırlanır...</span>}</button>)}</div>{!gallery.photos.length ? <p className="muted">Hələ paylaşılmış foto yoxdur.</p> : null}{selected ? <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="photo-modal" role="dialog" aria-modal="true" onClick={event => event.stopPropagation()}>{selected.previewUrl ? <img src={selected.previewUrl} alt={selected.originalFileName} /> : null}<button className="text-button" type="button" onClick={() => setSelected(null)}>Bağla</button></section></div> : null}</main>
}
