import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  az: { translation: { language: 'Dil', login: 'Daxil ol', register: 'Hesab yarat', profile: 'Profilim', logout: 'Çıxış', gallery: 'Qalereya', passwordReset: 'Şifrəni sıfırla', auth: { hostPortal: 'Host portal', welcome: 'Xoş gördük', createAccount: 'Hesab yaradın', emailVerification: 'Email təsdiqi', enterCode: 'Kodu daxil edin', resetPassword: 'Şifrəni sıfırla', newPassword: 'Yeni şifrə', accountRecovery: 'Hesab bərpası', manageMemories: 'Tədbir xatirələrinizi idarə etmək üçün daxil olun.', codeSentTo: '{{email}} ünvanına göndərilən 6 rəqəmli kodu yazın.', resetHelp: 'Email ünvanınıza gələn kod ilə yeni şifrə təyin edin.', email: 'Email', name: 'Ad', password: 'Şifrə', confirmationCode: 'Təsdiq kodu', showPassword: 'Şifrəni göstər', hidePassword: 'Şifrəni gizlət', passwordHint: 'Minimum 8 simvol və ən az 1 rəqəm.', wait: 'Gözləyin...', verify: 'Təsdiqlə', sendCode: 'Kod göndər', updatePassword: 'Şifrəni yenilə', resendCode: 'Kodu yenidən göndər', useAnotherEmail: 'Başqa email istifadə et', forgotPassword: 'Şifrəni unutmusunuz?', noAccount: 'Hesabınız yoxdur? Qeydiyyatdan keçin', backToLogin: 'Daxil olmağa qayıt', requestFailed: 'Sorğu tamamlanmadı.', codeSent: 'Yeni kod göndərildi.', resendFailed: 'Kod yenidən göndərilə bilmədi.', resetSent: 'Kod göndərildisə, aşağıdakı formda yeni şifrə təyin edin.', passwordUpdated: 'Şifrəniz yeniləndi. İndi daxil ola bilərsiniz.' } } },
  en: { translation: { language: 'Language', login: 'Sign in', register: 'Create account', profile: 'My profile', logout: 'Sign out', gallery: 'Gallery', passwordReset: 'Reset password', auth: { hostPortal: 'Host portal', welcome: 'Welcome back', createAccount: 'Create an account', emailVerification: 'Email verification', enterCode: 'Enter the code', resetPassword: 'Reset password', newPassword: 'New password', accountRecovery: 'Account recovery', manageMemories: 'Sign in to manage your event memories.', codeSentTo: 'Enter the 6-digit code sent to {{email}}.', resetHelp: 'Set a new password with the code sent to your email address.', email: 'Email', name: 'Name', password: 'Password', confirmationCode: 'Confirmation code', showPassword: 'Show password', hidePassword: 'Hide password', passwordHint: 'At least 8 characters and one digit.', wait: 'Please wait...', verify: 'Verify', sendCode: 'Send code', updatePassword: 'Update password', resendCode: 'Resend code', useAnotherEmail: 'Use another email', forgotPassword: 'Forgot your password?', noAccount: "Don't have an account? Sign up", backToLogin: 'Back to sign in', requestFailed: 'The request could not be completed.', codeSent: 'A new code was sent.', resendFailed: 'The code could not be resent.', resetSent: 'If a code was sent, set your new password below.', passwordUpdated: 'Your password was updated. You can now sign in.' } } },
  ru: { translation: { language: 'Язык', login: 'Войти', register: 'Создать аккаунт', profile: 'Мой профиль', logout: 'Выйти', gallery: 'Галерея', passwordReset: 'Сбросить пароль', auth: { hostPortal: 'Портал организатора', welcome: 'С возвращением', createAccount: 'Создать аккаунт', emailVerification: 'Подтверждение email', enterCode: 'Введите код', resetPassword: 'Сбросить пароль', newPassword: 'Новый пароль', accountRecovery: 'Восстановление аккаунта', manageMemories: 'Войдите, чтобы управлять воспоминаниями о мероприятии.', codeSentTo: 'Введите 6-значный код, отправленный на {{email}}.', resetHelp: 'Установите новый пароль с помощью кода из email.', email: 'Email', name: 'Имя', password: 'Пароль', confirmationCode: 'Код подтверждения', showPassword: 'Показать пароль', hidePassword: 'Скрыть пароль', passwordHint: 'Минимум 8 символов и одна цифра.', wait: 'Подождите...', verify: 'Подтвердить', sendCode: 'Отправить код', updatePassword: 'Обновить пароль', resendCode: 'Отправить код повторно', useAnotherEmail: 'Использовать другой email', forgotPassword: 'Забыли пароль?', noAccount: 'Нет аккаунта? Зарегистрируйтесь', backToLogin: 'Вернуться ко входу', requestFailed: 'Не удалось выполнить запрос.', codeSent: 'Новый код отправлен.', resendFailed: 'Не удалось отправить код повторно.', resetSent: 'Если код был отправлен, задайте новый пароль ниже.', passwordUpdated: 'Пароль обновлён. Теперь можно войти.' } } }
}

const savedLanguage = window.localStorage.getItem('bizden-language')
void i18n.use(initReactI18next).init({ resources, lng: savedLanguage && ['az', 'en', 'ru'].includes(savedLanguage) ? savedLanguage : 'az', fallbackLng: 'az', interpolation: { escapeValue: false } })
i18n.on('languageChanged', language => window.localStorage.setItem('bizden-language', language))

export default i18n
